name: leetdoad
on: 
  # Trigger the workflow to update Leetcode submission every month.
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  # Trigger the workflow to update Leetcode submission on every push.
  push:
    branches:
      - main
jobs:
  leetdoad-scraping:
    runs-on: ubuntu-latest
    steps:
      # Install go in the workflow.
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      # Install the latest version of leetdoad.
      - name: install leetdoad
        run: go install github.com/jiachengxu/leetdoad@latest
      # Checkout to the current project root.
      - name: checkout repo
        uses: actions/checkout@v2
      # Run leetdoad command in leetcode folder.
      - name: leetdoad scraping
        run: leetdoad
        working-directory: ./leetcode
        env: 
          LEETCODE_COOKIE: ${{ secrets.LEETCODE_COOKIE }}
      # Run go fmt
      - name: go fmt
        run: go fmt ./leetcode/...
      # Commit the change.
      - name: commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update leetcode solutions by leetdoad.
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Jiacheng Xu <xjcmaxwellcjx@gmail.com>
